project:
  type: book

book:
  title: "Summary Compilation: Advanced Computational Approaches for Medical Resource Scheduling"
  downloads: [pdf]

  search: 
    location: sidebar
    type: textbox
  
  author: 
    - name: "Oleksii Dovhaniuk"
      orcid: "0009-0003-2247-9323"
      email: "122119242@umail.ucc.ie"

      affiliations:
        - name: "University College Cork"
          department: "School of Computer Science and Technology"
          address: "Western Gateway Building, Western Road"
          city: "Cork"
          postal-code: "T12 YN60"
          
        - name: "The SFI Centre for Research Training in Al"
          city: "Cork"
        

  date: last-modified
  chapters:
    - index.qmd
    - summary/0001/index.qmd
    - summary/0002/index.qmd
    - summary/0003/index.qmd
    - summary/0004/index.qmd
    - summary/0005/index.qmd
    - summary/0006/index.qmd
    
    - summary/0008/index.qmd
    - summary/0009/index.qmd
    - summary/0010/index.qmd
    - summary/0011/index.qmd
    - summary/0012/index.qmd
    - summary/0013/index.qmd
    - summary/0014/index.qmd
    - summary/0015/index.qmd
    - summary/0016/index.qmd
    - summary/0017/index.qmd
    - summary/0018/index.qmd
    - summary/0019/index.qmd
    - summary/0020/index.qmd
    - summary/0021/index.qmd
    - summary/0022/index.qmd
    - summary/0023/index.qmd
    - summary/0024/index.qmd
    - summary/0025/index.qmd
    - summary/0026/index.qmd
    - summary/0027/index.qmd
    
    - summary/0029/index.qmd
    - summary/0020/index.qmd
    - summary/0031/index.qmd
    - summary/0032/index.qmd
    - summary/0033/index.qmd
    - summary/0034/index.qmd
    - summary/0035/index.qmd
    - summary/0036/index.qmd
    - summary/0037/index.qmd
    - summary/0038/index.qmd
    - legend.qmd
    - references.qmd

bibliography: references.bib
csl: ieee.csl


format:
  html:
    toc: true
    toc_float: true
    smooth-scroll: true
    toc-location: left
    comments:
      hypothesis: true
    theme: 
      light: litera
      dark: darkly
    mermaid:
      theme: neutral

  docx:
    toc: true

  pdf:
    documentclass: scrreprt
    toc: true
    number-sections: false
    colorlinks: true

toc: true
editor: visual

