project:
  type: book

book:
  title: "Summary Compilation: Advanced Computational Approaches for Medical Resource Scheduling"
  
  author: 
    - name: "Oleksii Dovhaniuk"
      orcid: "0009-0003-2247-9323"
      email: "122119242@umail.ucc.ie"

      affiliations:
        - name: "University College Cork"
          department: "School of Computer Science and Technology"
          address: "Western Gateway Building, Western Road"
          city: "Cork"
          postal-code: "T12 YN60"
          
        - name: "The SFI Centre for Research Training in Al"
          city: "Cork"

  date: last-modified
  chapters:
    - index.qmd
    - summary/AR0027IR20/index.qmd
    - legend.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    toc: true
    toc_float: true
    smooth-scroll: true
    toc-location: left
    comments:
      hypothesis: true
    citations-hover: true
    crossref-hover: true
    theme: 
      light: litera
      dark: darkly
    mermaid:
      theme: neutral

  docx:
    toc: true

  pdf:
    documentclass: scrreprt

toc: true
editor: visual

