# Legend {.unnumbered}


## Literature Material Groups {.unnumbered}

#### SR - Specialised Review {.unnumbered}
This group of studies represent literature reviews in the scope of medical resource scheduling problem related to focusing to operating theatres and related to this subject areas.

#### SO - Specialised Online Materials {.unnumbered}
Specialised Online posts, ads, commercial articles related to the medical resource scheduling problem, analytics of the healthcare for businesses, healthcare administrators, and technicians.

#### SC - Specialised Case Study {.unnumbered}
Specialised Case and application of the previous theory on practice;

#### SM - Specialised Idealised Model {.unnumbered}
Specialised Models developed specially for MRS problems;

#### SF - Specialised Full Study {.unnumbered}
Specialised Full work of developing model and implementing it;

#### ST - Specialised Theoretical Work {.unnumbered}
Specialised Theory works;

#### SS - Strategies for Healthcare Administrators {.unnumbered}
Specialised Administration related works;

#### AR - Review on the Alternatice Approaches out of Healthcare {.unnumbered}
Alternative Reviews of methods applicable to MRS;

#### AO - Alternative Online Resources {.unnumbered}
Alternative Online resources;

#### AC - Alternative Case Studies {.unnumbered}
Alternative Case which applied in a similar field or somehow related to MRS problems;

#### AF - Alternative Full Studies {.unnumbered}
Alternative Full work of developing model and implementing it;

#### AM - Developments of Alternative Models {.unnumbered}
Alternative Models for scheduling resources;

#### AT - Alternative Theory Works {.unnumbered}
Alternative Theory works;

#### AS - Strategies for Other Resource Management {.unnumbered}
The scheduling approaches which are not related to the healthcare, but can be adapted from other fields of reseach. (This is very similar to AT so possibly redundant)

#### HP - Healthcare Policies, Regulations, and Protocols {.unnumbered}
Healthcare policies, regulations, protocols, and rules which can differ from country to country and in some cases even from hospital to hospital.

#### OM - Other Materials {.unnumbered}
Other materials like posters, databases, memes, videos, etc.

#### NA - Undefined {.unnumbered}
Materials which are yet to be identified with one of the outlined above groups.




## Glossary {.unnumbered}

OT - Operating Theatre 

OR - Operating Room

OR&M - Operations Research and Management

LoS - Length of Stay

ICU - Intensive Care Unit

PACU - Post Anaesthetic Care Unit