project:
  type: book

book:
  title: "Systematic Review of Medical Resource Scheduling: Draft"
  author:
  author: 
    - name: "Oleksii Dovhaniuk"
      orcid: "0009-0003-2247-9323"
      email: "122119242@umail.ucc.ie"
      affiliations:
        - name: "University College Cork"
          department: "School of Computer Science and Technology"
          address: "Western Gateway Building, Western Road"
          city: "Cork"
          postal-code: "T12 YN60"
          
        - name: "The SFI Centre for Research Training in Al"
          city: "Cork"

    - name: "Grace Reidy"
      email: "Grace.Reidy1@hse.ie" 
      affiliations:
        - name: "Transforming Theatre Programme"
          department: "South South West Hospital Group Ireland"
          city: "Cork"
          
    - name: "Charlie Dineen"
      email: "charliedineen@rcsi.ie" 
      affiliations:
        - name: "Transforming Theatre Programme"
          department: "South South West Hospital Group Ireland"
          city: "Cork"
        - name: "Royal College of Surgeons in Ireland"
          city: "Dublin"

    - name: "Paul Redmond"
      email: "01@cuhcpc.ie " 
      affiliations:
        - name: "University College Cork"
          department: "Department of Surgery"
          city: Cork

    - name: "Mark Corrigan"
      orcid: "0000-0002-9615-6450"
      email: "mark.corrigan@ucc.ie" 
      affiliations:
        - name: "University College Cork"
          department: "Department of Surgery"
          city: "Cork"

        - name: "Transforming Theatre Programme"
          department: "South South West Hospital Group Ireland"
          city: "Cork"

        - name: "Cork Breast Research Center"
          city: "Cork"

    - name: "Sabin Tabirca"
      orcid: "0000-0003-0743-8227"
      email: "s.tabirca@ucc.ie "
      affiliations:
        - name: "University College Cork"
          department: "Department of Surgery (Academic)Máinliacht"
          address: "Cork University Hospital, Wilton"
          city: "Cork"
          postal-code: "T12 YN60"

        - name: "The SFI Centre for Research Training in Al"
          city: "Cork"
  abstract: "Here is the place for the abstract of this systematic literature review."
  date: last-modified
  chapters:
    - index.qmd
    - section/01_introduction.qmd
    - section/02_methods.qmd
    - section/03_results.qmd
    - section/04_discussion.qmd
    - section/05_other_information.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    toc: true
    toc_float: true
    smooth-scroll: true
    toc-location: left
    comments:
      hypothesis: true
    citations-hover: true
    crossref-hover: true
    theme: 
      light: litera
      dark: darkly
    mermaid:
      theme: neutral
  docx:
    toc: true
  pdf:
    documentclass: scrreprt

editor: visual

