# Results

## Study Selection

### Flow of Studies

<div style='color: teal;'>
Report, ideally using a flow diagram, the number of: records identified; records excluded before screening; records screened; records excluded after screening titles or titles and abstracts; reports retrieved for detailed evaluation; potentially eligible reports that were not retrievable; retrieved reports that did not meet inclusion criteria and the primary reasons for exclusion; and the number of studies and reports included in the review. If applicable, also report the number of ongoing studies and associated reports identified.

If the review is an update of a previous review, report results of the search and selection process for the current review and specify the number of studies included in the previous review.

If applicable, indicate in the PRISMA flow diagram how many records were excluded by a human and how many by automation tools.
</div>




### Excluded Studies

<div style='color: teal;'>
Cite studies that might appear to meet the inclusion criteria, but which were excluded, and explain why they were excluded.
</div>
    





## Study Characteristics

<div style='color: teal;'>
Cite each included study.

Present the key characteristics of each study in a table or figure (considering a format that will facilitate comparison of characteristics across the studies).

If the review examines the effects of interventions, consider presenting an additional table that summarises the intervention details for each study.
</div>






## Risk of Bias in Studies

<div style='color: teal;'>
Present tables or figures indicating for each study the risk of bias in each domain/component/item assessed (e.g. blinding of outcome assessors, missing outcome data) and overall study-level risk of bias.

Present justification for each risk of bias judgement, for example in the form of relevant quotations from reports of included studies.

If assessments of risk of bias were done for specific outcomes or results in each study, consider displaying risk of bias judgements on a forest plot, next to the study results.
</div>






## Results of Individual Studies

<div style='color: teal;'>
For all outcomes, irrespective of whether statistical synthesis was undertaken, present for each study summary statistics for each group (where appropriate). For dichotomous outcomes, report the number of participants with and without the events for each group; or the number with the event and the total for each group (e.g. 12/45). For continuous outcomes, report the mean, standard deviation and sample size of each group.

For all outcomes, irrespective of whether statistical synthesis was undertaken, present for each study an effect estimate and its precision (e.g. standard error or 95% confidence/credible interval). For example, for time-to-event outcomes, present a hazard ratio and its confidence interval.

If study-level data is presented visually or reported in the text (or both), also present a tabular display of the results.

If results were obtained from multiple data sources (e.g. journal article, study register entry, clinical study report, correspondence with authors), report the source of the data.

If applicable, indicate which results were not reported directly and had to be computed or estimated from other information.
</div>







## Results of Syntheses

In this section the outcomes of the analysis syntheses on the papers combined into three subgroups that present data-driven, process-driven, and hybrid solutions to the medical resource scheduling problem. The meta-analysis demonstrates the advantages and disadvanatages of the approaches in scope of robustness, applocability, and the complexoty of the models. 




### Characteristics of Contributing Studies

The simplest and with the least impact characteristic which indicates the precision of the study outcome is number of cited papers by the study.  

<div style='color: teal;'>
Provide a brief summary of the characteristics and risk of bias among studies contributing to each synthesis (meta-analysis or other). The summary should focus only on study characteristics that help in interpreting the results (especially those that suggest the evidence addresses only a restricted part of the review question, or indirectly addresses the question).

Indicate which studies were included in each synthesis (e.g. by listing each study in a forest plot or table or citing studies in the text).
</div>




### Results of Statistical Syntheses

The subsection demonstrates results in seven investigated aspects: robusntess, applicability, complexity, integtry of the solutions, also what levels of desicion-making are the most often researched for the last three years, what countries have the most scientific potential in scope of human resources, and finally the most progressive countries in terms of researching for needs of a specific hospitals. All this aspects have their own subgroups of data-driven and process-driven approaches, and some topycs are overlapping to showcase discribution of the study in the medical resource scheduling. 

#### Data on Robustness

For multiple reasons the parameter of robustness is much higher for the theoretical stadies then in practical applicable solutions. The first reason is that the number of data-driven, in particular deep learning, approaches is drastically increased for the last years. The focus on historical data is beneficial for applicability of the result, but in cost of robustness of the model, which makes it harder to apply the same model for multiple solutions but with slitelly different environment and input data. Second lab models are more idealised, and thus more inclusive than complex realistic models. And finally, most of the hospitals in the studies work almost independantly for other healthcare facilities especially with facilities in other countries. This strategy gains quick local benefits but also reduces generasability of the hospital protocols for other developing hospitals.

THE PLOT SHOWCASES ROBUSTNESS FOR STUDIES ON DATA-DRIVEN, PROCESS-DRIVEN, AND HYBRIT APPROACHES FOR THE AT-LEAST LAST THREE YEARS 


#### Data on Applicability 



THE PLOT SHOWCASES APPLICABILITY FOR STUDIES ON DATA-DRIVEN, PROCESS-DRIVEN, AND HYBRIT APPROACHES FOR THE AT-LEAST LAST THREE YEARS 


#### Data on Complexity

The complexity and the applicability of the medical resource scheduling problem are clossely related. Especially when there is no way to compare the developing process and the design solutiong amoung themselves. ... 

THE PLOT SHOWCASES COMPLEXITY FOR STUDIES ON DATA-DRIVEN, PROCESS-DRIVEN, AND HYBRIT APPROACHES FOR THE AT-LEAST LAST THREE YEARS 


#### Data on Integrated Solutions

The results on level of integrations are simmilar to the complexity characteristic of the reviewed studies. Nevertheless, complex scheduling is not always highly-integrated. The problem deffinition can be consentraited specifically on-to operating theatre and consider all possible timing charateristics of the scheduling problems but not take into account upstream and downstream capacities. Therefore, complexity relates to depth and width of the problem components when integrity highlights only the width of the scheduling problem.

THE PLOT SHOWCASES COMPLEXITY FOR STUDIES ON DATA-DRIVEN, PROCESS-DRIVEN, AND HYBRIT APPROACHES FOR THE AT-LEAST LAST THREE YEARS 


#### Data on Level of Desicion-Making


#### The Human-Scientific Potential


#### Localisation of the Studies

<div style='color: teal;'>
Report results of all statistical syntheses described in the protocol and all syntheses conducted that were not pre-specified.

If meta-analysis was conducted, report for each:
the summary estimate and its precision (e.g. standard error or 95% confidence/credible interval)
measures of statistical heterogeneity (e.g. 𝜏2, I2, prediction interval)

If other statistical synthesis methods were used (e.g. summarising effect estimates, combining P values), report the synthesized result and a measure of precision (or equivalent information, for example, the number of studies and total sample size).

If the statistical synthesis method does not yield an estimate of effect (e.g. as is the case when P values are combined), report the relevant statistics (e.g. P value from the statistical test), along with an interpretation of the result that is consistent with the question addressed by the synthesis method.

If comparing groups, describe the direction of effect (e.g. fewer events in the intervention group, or higher pain in the comparator group).

If synthesising mean differences, specify for each synthesis, where applicable, the unit of measurement (e.g. kilograms or pounds for weight), the upper and lower limits of the measurement scale (e.g. anchors range from 0 to 10), direction of benefit (e.g. higher scores denote higher severity of pain), and the minimally important difference, if known. If synthesising standardised mean differences, and the effect estimate is being re-expressed to a particular instrument, details of the instrument, as per the mean difference, should be reported.
</div>




### Results of Investigation of Heterogeneity

For the study of this scope the identification of the studies which can be effectively compared and analysed on bias within the sertain borders is not a trivial task. First of all, even the medical resource scheduling problem goes under umbrella of one term, there are numerouse problems which this term contains. And even, for example, if the operating theatre scheduling is considered as a focal point of the research, the problem formulationions for that segment of scheduling problems varies greatly. Therefore, to unify measuring criteria for the reviewed, it was desided to compare the studies based on the three metrices: robustness, applicability, and complexity.

**PRESENT THE GENERAL RESULTS WITH HETEROGENEITY TABLE FOR DATA-DRIVEN, PROCESS-DRIVEN, AND HYBRID SOLUTIONS**


#### Robustness:

The data-driven methods show better robustness then other approaches. The wide data used in the data-driven algorithm increases the focus of the modules to a specific environments. This make machine learning approaches less scalable for different scenarios in the same area of schedulig medical resources. If consider some general advisory system which will serve a veriaty of hospitals there is a requirements for protocols of processes to which the system will resert when there is no hystoric data available.

**PRESENT FOREST TREES OF WORKS REGARDIGN ROBUSTNESS FOR EACH SUBGROUP BASED ON PROBLEM DEFFINITION**


#### Applicability:

The major consern is that most of the work consentraited on the non-applicable solutions. Hopefully the interest in deep learning solutions tip this scale in the favor of more applicability of the scheduling models. It is easy to see that data-driven and hybrid models are producing much more practical solutions then process driven approaches. The advantage of deep learning algorithms is in finding solutions depending directrly on the historic data without a layer of abstraction, which often oversimplifies the problems.

**PRESENT FOREST TREES OF WORKS REGARDIGN APPLICABILITY FOR EACH SUBGROUP BASED ON PROBLEM DEFFINITION**


#### Complexity:

Only small portion of the research are considered complex with at least 0.8 of above score. One of the highly possible reasons for this is that even the authors who eventually build solutions for complex models start with the smaller simpler tasks to test their theory and understand the diractions of improvement. The mean value suggest that the researchers are still mostrly intrested in simple and midium-complexity models. 

**PRESENT FOREST TREES OF WORKS REGARDIGN COMPLEXITY FOR EACH SUBGROUP BASED ON PROBLEM DEFFINITION**




### Results of Sensitivity Analyses

The sensetivity analysis is condacted focusing on the quality and count of studies, and also on robustness, applicability, and complexity of the solutions. For the leveraging parameters the country income, population, and results of the PISO2014 international survey are taken into account. Also the model is available by the **LINK** which predicts the research state in the area of advanced computational methods for medical resource scheduling based on the input values underlined in the previous sentance. According to the results, the next trends can be seen below:

**PRESENT TWO VARIENTIONS OF PLOTS: (I) X AXES REPRESENTS INCOME, Y AXES REPRESENTS ONE OF 4 ASPECTS: QUALITY OF RESEARCH, ROBUSTNESS, APPLICABILITY, AND COMPLEXITY OF THE SOLUTIONS, SIZE OF THE BOOBLE REPRESENTS THE POPULATION SIZE; (II) X AXES SOME GENERAL PARAMETER FORM PISO2014, THE REST IS THE SAME AS IN THE PREVIOUS TYPE (I) PLOTS** 

The lack of information on published papers due to artificial limitation to only English emplies that the presented analysis is not full but still representative. The forest plots presented below show veriaty in the results. 

**THE RESULTS OF SENSITIVITY ANALYSES VISUALLY USING FOREST PLOTS**

The outcomes of the sensitivity analysis are also generalised by analysing their heterogeneity. 

**ALSO CONSIDER SHOWING HETEROGENEITY PLOTS OR TABLES GENERALISING RESULTS FRON FOREST PLOTS**






## Reporting Biases

There are high interest in the machine learning trends specially in deep learning, which clearly makes the research community favor these approaches over the other existing methods for medical resource scheduling. To investigate the existing biases when commes to synthesysing the advance computational system to support desicions of the healthcare managers the availability and the type of the outcomes of the studies are considered.

The percentyle of the possitive findings is much higher in research with deep learning approaches then in all other approchers. These may possibly indicate that the studies with the negative findings was not approved in reviewed journals, the results have been adjusted, or perspective on the outcomes have been shifted toward more favorable results. Just by difference between positive and negative outcomes it is impossible to state deffinatrly about the current situation in the medical resource scheduling. 

**CHART WITH PERSENTAGES OF POSITIVE AND NEGATIVE OUTCOMES FOR DIFFERENT SOLUTION APPROACHES IN REGARD TO SPECIFIED PROBLEM, POSSIBLY HEAT MAP COULD BE USEFULL**

For more in-depth analysis of the materials the solutions' advantages, disadavantages, and also the proofs of the authors statement have been collected for each publication which gone over the focus stage of the review. Based on the gathered data the quantitative assessments of risk of bias was conducted. The rate of the proffed statements to the overal namber of statements have been calculated for the problem-solution pares. The results of the analysis are displaied in the charts below.

**NUMBER OF CHARDS DEMONSTRATING RISK OF BIASES TOWARD PROS AND CONS OF EACH SOLUTION IN THE CORRESPONDED HEALTHCARE SCHEDULING PROBLEM**






## Certainty of Evidence

The certainty of the evidence in the reviewed studies are rated with five-scale grade. Where are five critarias of certainty, each of the reached criteria gains a point of certainty to the reviewed material. The grading systems is created in the way that for most of the cases the next point of certainty can be gained if the requirements for the previous points are meat:

- 1st point: The resutls of the research are mentioned in the body of the report paper with explanation how the results were obtained.

- 2nd point: The process of reaching the findings of the study is clearly stated. The results are mention in body of the research and underlined in the conclusions of the work. 

- 3rd point: The output of the research is highlighted in the short summaries of the paper (abstract, conclusions, or discussions). The authors of the work presented the data in structured digestible form.

- 4th point: The findings demonstrated with charts or tables, and there is a link to the manuscripts, research data, or additional supplimentary materials. However, the original data is not accessable, or in order to access the data, other researchers need to make a request, fully andertend the architecture of the storage platform, where the data was reserved.  

- 5th point: The results are presented in a table and the collected data during the research is fully available and easally accessable for the replication of the results by other investigators. The data in the presented tables is consistant with the values presented in the text and the raw data of the research.

**PROVIDE A TABLE OR/AND CHART WITH CERTAINTY GRADES FOR THE REVIEWED WORKS**

The average certainty of the results is belove medium possible level on the certainty scale. The main reason for this is complications to get medical records available as open-source database. However, if researchers gave more attention to the reproducibility of the research, this score would be much higher even with the existing challenges in the healthcare industry.

**PROVIDE A DETAILED TABLE OR/AND CHART WITH CERTAINTY GRADES FOR THE REVIEWED WORKS RELATED TO THE LOCATION OR OTHER CHARACTERISTICS OF THE WORK**